# Generated by Django 4.2.2 on 2023-07-20 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={},
        ),
        migrations.AlterModelTable(
            name='usermodel',
            table='auth_user',
        ),
    ]
